### PR TITLE
Upgrade to Spring Boot 2.1.6 for both master tool and scdf-app-repo

### LINKED ISSUE #8: Upgrade to Spring Boot 2.1.6 for both master tool and scdf-app-repo
Upgrade from Spring Boot 2.0.3.RELEASE to 2.1.6.RELEASE

### PR DESCRIPTION
**Pull request by jackycct**
Resolves https://github.com/spring-cloud-stream-app-starters/scdf-app-tool/issues/8

### CODE REVIEW

**Comment by jackycct** [comment]
Can you please review this change and merge it? many thanks

**Comment by sabbyanandan** [comment]
Hi, @jackycct. Thank you for the PR! Could you share the background as to why being on the latest Boot 2.1.x is a requirement for you? Just curious. And, it'd be helping decide whether to do a tactical release vs. include it in the next release train.

Also, any details on how you're using this tool would be useful, too.

**Comment by jackycct** [comment]
Hi @sabbyanandan 
I am using this tool in my enterprise. This is used to ensure the apps are downloaded from control environment, not maven repo.
We intended to use latest spring boot as 2.0 is in maintain status. We love to be more agile so appreciate if you can release in this sprint.

Thanks

**Comment by sabbyanandan** [comment]
Alright, we will check it out. One other thing, though. 

Are you using Spring Cloud Data Flow with it or are you simply just using it as a standalone tool in replacement of artifactory? If it is the latter, what types of applications are you serving with this tool?

**Comment by jackycct** [comment]
We are using it with spring cloud data flow. We are going to promote SCDF 2.1 to our organisation.

Thank you so much. Happy to exchange ideas on SCDF

**Comment by dturanski** [comment]
Thank you @jackycct !  Merged.

**Comment by sabbyanandan** [comment]
@jackycct: The [0.0.4 release](https://github.com/spring-cloud-stream-app-starters/scdf-app-tool/releases/tag/v0.0.4) is complete. Thank you for your contribution! I look forward to learning more about your use-cases.

**Pull request closed without merging**
